In [1]:
q1_sales = [23,45,56]
q2_sales = [33,65,86]
q3_sales = [43,55,86]
q4_sales = [53,55,96]


import numpy as np
print('done')

done


In [2]:
np.__version__

'2.1.3'

In [3]:
import matplotlib.pyplot as plt
print('done')

done


In [8]:
arr_0 = np.array(5678)
arr_0.ndim

0

In [9]:
arr_1 = np.array([124,3,4,3456])

print(arr_1)

[ 124    3    4 3456]


In [10]:
arr_1.ndim

1

In [11]:
arr_2 = np.array([[1,2,34],
                 [3,4,5]])
arr_2

array([[ 1,  2, 34],
       [ 3,  4,  5]])

In [12]:
arr_2.ndim

2

In [13]:
arr_3 = np.array([[[12,4,354]]])

arr_3

array([[[ 12,   4, 354]]])

In [14]:
arr_3.ndim

3

In [15]:
arr_2.shape

(2, 3)

In [16]:
arr_2

array([[ 1,  2, 34],
       [ 3,  4,  5]])

In [17]:
arr_3.shape

(1, 1, 3)

In [18]:
arr_3

array([[[ 12,   4, 354]]])

In [19]:
arr_3_new = np.array([[[1,2,3],
                     [3,4,5]]])
arr_3_new

array([[[1, 2, 3],
        [3, 4, 5]]])

In [20]:
arr_3_new.shape

(1, 2, 3)

In [21]:
arr_3_new_again = np.array([[[1,2,3],
                             [3,4,5]],

                            [[11,12,13],
                             [13,14,15]]])
arr_3_new_again

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[11, 12, 13],
        [13, 14, 15]]])

In [22]:
arr_3_new_again.shape

(2, 2, 3)

In [23]:
arr_3_3 = np.array([[[1,2,3],[2,3,4],[2,3,4]],
         [[1,2,3],[2,3,4],[2,3,4]],
         [[1,2,3],[2,3,4],[2,3,4]]])


In [24]:
arr_3_3.shape

(3, 3, 3)

In [25]:
arr_3_3

array([[[1, 2, 3],
        [2, 3, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [2, 3, 4]]])

In [26]:
arr_3_5 = np.array(
                    [
                    [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
                    [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
                    [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
                    ]
                   )



In [27]:
arr_3_5

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [28]:
arr_3_5.ndim

3

In [29]:
arr_3_5.shape

(3, 5, 5)

In [30]:
arr_3_5.size

75

In [31]:
np.random.randint(1,100,(5,5))

array([[36, 82, 29, 28, 44],
       [78, 98, 23, 23,  5],
       [80, 29, 34, 49, 35],
       [58, 92, 42, 87, 57],
       [ 6, 86, 23, 72,  5]], dtype=int32)

In [32]:
np.random.randint(1,100,(3,3,3))

array([[[ 1, 79, 17],
        [88, 93, 43],
        [99, 66, 59]],

       [[51, 62, 60],
        [83,  7, 63],
        [13, 90, 32]],

       [[94, 13, 32],
        [33, 80, 50],
        [ 8, 91, 79]]], dtype=int32)

In [33]:
ar = np.random.randint(1,100,(5,3,3,5))
ar

array([[[[70, 26, 81, 27, 64],
         [ 9, 88, 62, 80, 67],
         [22, 38, 47, 87, 98]],

        [[74, 50, 67, 26,  6],
         [44, 13, 43, 25, 81],
         [32, 57, 19, 16,  3]],

        [[56,  2, 81, 17, 51],
         [96, 48, 91, 21, 31],
         [14, 38, 84,  5, 61]]],


       [[[10, 61, 78, 20, 93],
         [74, 18, 65, 81, 63],
         [99, 64, 67,  3, 85]],

        [[74,  7, 34, 95,  6],
         [35, 58, 26, 23, 66],
         [88, 61, 46, 92, 59]],

        [[96,  4, 65, 90, 54],
         [11, 26, 79, 21, 66],
         [62, 80, 80, 34, 17]]],


       [[[74, 35, 67, 83, 51],
         [66, 99, 93, 33, 38],
         [84, 68, 50, 48, 87]],

        [[10, 90, 57, 60, 47],
         [75, 73, 47,  9, 18],
         [68, 77, 51, 65, 39]],

        [[22, 36, 81, 80, 28],
         [ 5, 80, 39, 53, 20],
         [67, 32,  3,  8, 28]]],


       [[[13, 17, 98, 11, 25],
         [33, 80, 75, 65,  6],
         [20, 82, 37, 87, 78]],

        [[67, 24, 31, 46, 24],
         [99,

In [34]:
final_arr = np.random.randint(1,50,(3,3,3))
final_arr

array([[[21,  2, 23],
        [ 4, 48, 41],
        [48, 28,  2]],

       [[40, 29, 47],
        [44, 18, 29],
        [41, 17, 20]],

       [[29, 24, 49],
        [36,  9, 26],
        [21, 25, 10]]], dtype=int32)

In [35]:
final_arr + 100

array([[[121, 102, 123],
        [104, 148, 141],
        [148, 128, 102]],

       [[140, 129, 147],
        [144, 118, 129],
        [141, 117, 120]],

       [[129, 124, 149],
        [136, 109, 126],
        [121, 125, 110]]], dtype=int32)

In [36]:
final_arr - 100

array([[[-79, -98, -77],
        [-96, -52, -59],
        [-52, -72, -98]],

       [[-60, -71, -53],
        [-56, -82, -71],
        [-59, -83, -80]],

       [[-71, -76, -51],
        [-64, -91, -74],
        [-79, -75, -90]]], dtype=int32)

In [37]:
final_arr * 100

array([[[2100,  200, 2300],
        [ 400, 4800, 4100],
        [4800, 2800,  200]],

       [[4000, 2900, 4700],
        [4400, 1800, 2900],
        [4100, 1700, 2000]],

       [[2900, 2400, 4900],
        [3600,  900, 2600],
        [2100, 2500, 1000]]], dtype=int32)

In [38]:
final_arr ** .5

array([[[4.58257569, 1.41421356, 4.79583152],
        [2.        , 6.92820323, 6.40312424],
        [6.92820323, 5.29150262, 1.41421356]],

       [[6.32455532, 5.38516481, 6.8556546 ],
        [6.63324958, 4.24264069, 5.38516481],
        [6.40312424, 4.12310563, 4.47213595]],

       [[5.38516481, 4.89897949, 7.        ],
        [6.        , 3.        , 5.09901951],
        [4.58257569, 5.        , 3.16227766]]])

In [45]:
import numpy as np
ar_1 = np.random.randint(1,10,10)
ar_1

array([4, 6, 9, 6, 1, 4, 7, 5, 7, 5], dtype=int32)

In [46]:
a_2 = np.random.randint(1,10,(3,3))
a_2

array([[4, 6, 7],
       [3, 7, 4],
       [8, 1, 2]], dtype=int32)

In [47]:
print(a_2[1,1])

7


In [48]:
a_2[0:3,0:3]

array([[4, 6, 7],
       [3, 7, 4],
       [8, 1, 2]], dtype=int32)

In [49]:
a_2[:3,:3]

array([[4, 6, 7],
       [3, 7, 4],
       [8, 1, 2]], dtype=int32)

In [50]:
a_2[::2,::2]

array([[4, 7],
       [8, 2]], dtype=int32)

In [51]:
a_2[::2,::2] = 100

In [52]:
a_2

array([[100,   6, 100],
       [  3,   7,   4],
       [100,   1, 100]], dtype=int32)

In [53]:
arr_3 = np.random.randint(1,100,(3,3,3))
arr_3

array([[[34, 22, 70],
        [48, 66, 62],
        [32, 15, 46]],

       [[85, 94, 25],
        [60, 16, 38],
        [51, 51, 47]],

       [[47, 26, 71],
        [77, 90, 43],
        [22,  3, 15]]], dtype=int32)

In [54]:
arr_3[2,0,2]

np.int32(71)

In [55]:
arr_3[:,::2,::2]

array([[[34, 70],
        [32, 46]],

       [[85, 25],
        [51, 47]],

       [[47, 71],
        [22, 15]]], dtype=int32)

In [56]:
arr_3[:,::2,::2].reshape(3,4)

array([[34, 70, 32, 46],
       [85, 25, 51, 47],
       [47, 71, 22, 15]], dtype=int32)

In [57]:
arr_3[:,::2,::2].reshape(4,3)

array([[34, 70, 32],
       [46, 85, 25],
       [51, 47, 47],
       [71, 22, 15]], dtype=int32)

In [58]:
arr_3[2,:,:]

array([[47, 26, 71],
       [77, 90, 43],
       [22,  3, 15]], dtype=int32)

In [59]:
# Shape
# Size
# ndim
# dtype
# slicing and indexing
# array
# random.randint
# arange
# linspace
# concat
# hstack
# vstack
# mean
# sum
# median
# sort
# cumsum
# argmin
# argmax
# argsort
# where
# clip
# Broadcasting

In [60]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'arr

In [62]:
plt.imshow(arr)

NameError: name 'arr' is not defined